### ISSUE TITLE
TS throw `Type instantiation is excessively deep and possibly infinite` when there are loads of keys

### ISSUE THREAD

**Issue by jigsawye** [i18next/react-i18next#1222]
## 🐛 Bug Report

I have a locale resource which has over than 2500 keys.
After I followed #1193 to set correct types of my project, the errors just happened.

## To Reproduce

<img width="1185" alt="screencapture 2020-12-10 下午3 55 40" src="https://user-images.githubusercontent.com/8567270/101737700-3464eb80-3b00-11eb-9318-d8fe6d49bcd4.png">

## Expected behavior

No errors

## Your Environment

- *runtime version*: node v12.19
- *react-i18next version*: 11.8.0
- *i18next version*: 19.8.4
- *os*: Mac

**Comment by jamuhl** [comment]
@pedrodurek you got an idea?

**Comment by DCzajkowski** [comment]
Isn't this caused by a namespace? I believe namespaces are not supported by type checking currently — I may be wrong though 🙂

**Comment by pedrodurek** [comment]
Hey @DCzajkowski, actually it does. It supports all cases, single, multiple and no namespace passed. And without augmentation the Resources type, it should work as before in the v11.7.4. So this feature which types all `keys` and return `type` of t function is optional.

**Comment by DCzajkowski** [comment]
> Hey @DCzajkowski, actually it does. It supports all cases, single, multiple and no namespace passed.

Good to know namespaces are supported, thanks!

> without augmentation the Resources type, it should work as before in the v11.7.4. So this feature which types all keys and return type of t function is optional.

Hm, it didn't work for me. Without type augmentation I was getting type errors for keys :/ I can give you more information, but I don't have time at this moment. Let me know 😉

**Comment by pedrodurek** [comment]
Hey @jigsawye, we've performed tests with more them 5k keys and it worked perfectly, so 2.5k keys shouldn't be a problem. Could you provide some extra info so we can test the closest scenario that you have there?

1 - Do you know approximately how deep the keys are?
2 - Under your keys, do you have cases where you have arrays inside other arrays, like this?
```
{
  title: 'x'
  list: [['x', 'y'], ['x', 'y'], ['x', 'y']],
  list2: [{
    subList: [{
      title: 'x'
    }]
  }]
}
```
3 - How many namespaces do you have?

We're working on the documentation for these new types. So it'd be great to know whether there is a limitation or not. If there is, our idea is to report those limitations to the Typescript team.

**Comment by pedrodurek** [comment]
Hey @DCzajkowski, even using the last version v11.8.3? If so, could you post the error here?

**Comment by DCzajkowski** [comment]
@pedrodurek Thanks for letting me know. I have just upgraded to v11.8.3 and there are no breaking changes anymore, yay!

Just FYI: the initial error I was getting was not caused by type checking on keys, but on our usage of the `WithTranslation` type. In 11.8.0 it was expecting and argument `<N>`, which wasn't provided in our case. It was a long day, sorry for causing confusion 🤭😅

**Comment by jigsawye** [comment]
Hi @pedrodurek, thank you for your quick response.

The Resources type is like:

```ts
export = LocaleResource;
declare const LocaleResource: {
    ns1: {
        key1: string;
        key2: string;
        key3: string;
// ...
```

I have 48 namespaces. And there are just loads of keys under every namespaces, no array or object.

Actually I’ve already reproduced the error on [CodeSandbox](https://codesandbox.io/s/react-i18next-type-excessively-deep-ihihk).
Please have a look. Thanks!

**Comment by pedrodurek** [comment]
Hey @jigsawye, thanks for your help. The bug isn't related to the number of keys, but more with the number of namespaces. It seems to be a typescript limitation/bug. We can see on the examples below, that with 22 namespaces it doesn't throw any error, but from 23 it does. The type is inferred properly and there are no compilation time issues though, it's just a warning.

* [22 namespaces](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.1.2#code/C4TwDgpgBAShDOB7ArgJwMYINIRAHgBUoBeKAa10QDNYEUMEA+EqAbQIF0oIAPYCAHYATeGwEQAbhFRcA-FHjBUASwEBzKAC4oBANwAofQHojUAHKJUAWwCGAG2UAvaPFVq70ATasIwNzPqgkFAA8lbKwACCqKg2IAAKqIhg8ITMpACiPOh2yEIQhAA05JQ0NgIgrByMBkHQkWCQwjggqVgAjMVYAEzpUAAGACQA3h1QAGQKSm4AvgB0I2ER0bEJSSl4PcyTiirqM-214NAW1vZOEN1FUFgsFCDUOn23vPzCovePBPpQUPIErCwXFeghEUEQACMAFYQdDAH5-KANJpCFptYqfGgAoHMAA+SMaoLRm2Kp1sDmcV2x1UYCO04ikqDpUAZ0iOwTJ52caTupR0UHxnIplzSBmMpiFFygVmQdmAyjAHhZ3l8-gQgWOUAAqgJlIgBAREABJAT8VDwWHy-V4LV9AAUWu4fFBonKIAR8jtZG0WoAlCRmBJEMohMzWah-SD3lAvdpVFRpFAjf7iIHg6HfvIjWHJGyNcEADI2RQhKg80g6vUG42m6QWuFVvAIohRsFuxF2lPMIj03NM5it0SdgNQeOJmAe2A5xns+qE4RmADKeDMXT6Q2GZgmUz2ahmmhGtx2032h3zJ0s5IuAFlZfLro7ByUHljigWWEWS2XbX130+tZOyKgkueAFqSl5cgUAIFjSArmBBwq3nKyjXFkOR5AUWpvowtK-L2M6GHU5gqvAfiYCwcBIGgmDwC0cGUfQNEtFUYpEQQABiyACOgLQrsURCkAx1FMCwW5Pl6fIEL6VSTpKzhIfeBCkqwAjIFYELSNUzJic60aYjoskIRchCsGYWl4TubisZqHFcQ21o6W8YJmCRZEQH0mxOk5oi2dxvFmDhdoIvc2hYPoXaWeo1nBFqFoELEAjwHYNhWgIlFgPqForl5LrET4pFqn0wwIsA2i+fZAgrjU+gzGK+Q5DYqDQFQdmpVAyBxQlSUpY2La6c5rmFXaiWyGVvo+p15Tdal6WZVB1XGAAVFAAC0a3rRtm1bdtO3bfoy2-IdR3HbFdZQOgiD5Md103VAi36Ltj1Pc962LUYhGakJDCiKQdSPE1VHfWKF2JcAUAA4xCAsMVvyJe02gw4dIVQIjR3wMgEItNoADkuxuNjCK-DMCIzIUCKJd0COE8+ON4+oBNE2TsPwAAzFTR3I7jJ5qAzUCk+T8AACzs0juC09zvP88zACsIu-JzdM8yTTMsvAABscs01AXO7pLKuJQA7JrCsS8rAsABzG2L2uK3rAsAJxWyA4u62bzPtAADE7Lv427qvtPDKPUybruMwL7SU0HHPWzrvth+7bNR6Lzs26b8f+7LSfyzHtt+3DGtZ1rsf03n8DtEbhch3HfP62XluVznac1+HjsNynxdK+nFNe23Psl138DdIHqNF7nA-dJHI9V-3zczFAxbnZlwDA0vKNQGDc+kB1EDxVNyWpXa2Nw9jvoGCDijgwgd4sMAh-3HM6OY7gJ8r6Da+lev3R8yw2+74l+9VjtKwI+ZdsYcFPvoc+YMAZ3i-r9boh84aaHvo-FoL99BAA)
* [23 namespaces](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.1.2#code/C4TwDgpgBAShDOB7ArgJwMYINIRAHgBUoBeKAa10QDNYEUMEA+EqAbQIF0oIAPYCAHYATeGwEQAbhFRcA-FHjBUASwEBzKAC4oBANwAofQHojUAHKJUAWwCGAG2UAvaPFVq70ATasIwNzPqgkFAA8lbKwACCqKg2IAAKqIhg8ITMpACiPOh2yEIQhAA05JQ0NgIgrByMBkHQkWCQwjggqVgAjMVYAEzpUAAGACQA3h1QAGQKSm4AvgB0I2ER0bEJSSl4PcyTiirqM-214NAW1vZOEN1FUFgsFCDUOn23vPzCovePBPpQUPIErCwXFeghEUEQACMAFYQdDAH5-KANJpCFptYqfGgAoHMAA+SMaoLRm2Kp1sDmcV2x1UYCO04ikqDpUAZ0iOwTJ52caTupR0UHxnIplzSBmMpiFFygVmQdmAyjAHhZ3l8-gQgWOUAAqgJlIgBAREABJAT8VDwWHy-V4LV9AAUWu4fFBonKIAR8jtZG0WoAlCRmBJEMohMzWah-SD3lAvdpVFRpFAjf7iIHg6HfvIjWHJGyNcEADI2RQhKg80g6vUG42m6QWuFVvAIohRsFuxF2lPMIj03NM5it0SdgNQeOJmAe2A5xns+qE4RmADKeDMXT6Q2GZgmUz2ahmmhGtx2032h3zJ0s5IuAFlZfLro7ByUHljigWWEWS2XbX130+tZOyKgkueAFqSl5cgUAIFjSArmBBwq3nKyjXFkOR5AUWpvowtK-L2M6GHU5gqvAfiYCwcBIGgmDwC0cGUfQNEtFUYpEQQABiyACOgLQrsURCkAx1FMCwW5Pl6fIEL6VSTpKzhIfeBCkqwAjIFYELSNUzJic60aYjoskIRchCsGYWl4TubisZqHFcQ21o6W8YJmCRZEQH0mxOk5oi2dxvFmDhdoIvc2hYPoXaWeo1nBFqFoELEAjwHYNhWgIlFgPqForl5LrET4pFqn0wwIsA2i+fZAgrjU+gzGK+Q5DYqDQFQdmpVAyBxQlSUpY2La6c5rmFXaiWyGVvo+p15Tdal6WZVB1XGAAVFAAC0a3rRtm1bdtO3bfoy2-IdR3HbFdZQOgiD5Md103VAi36Ltj1Pc962LUYhGakJDCiKQdSPE1VHfWKF2JcAUAA4xCAsMVvyJe02gw4dIVQIjR3wMgEItNoADkuxuNjCK-DMCIzIUCKJd0COE8+ON4+oBNE2TsPwAAzFTR3I7jJ5qAzUCk+T8AACzs0juC09zvP88zACsIu-JzdM8yTTMsvAABscs01AXO7pLKuJQA7JrCsS8rAsABzG2L2uK3rAsAJxWyA4u62bzPtAADE7Lv427qvtPDKPUybruMwL7SU0HHPWzrvth+7bNR6Lzs26b8f+7LSfyzHtt+3DGtZ1rsf03n8DtEbhch3HfP62XluVznac1+HjsNynxdK+nFNe23Psl138DdIHqNF7nA-dJHI9V-3zfM90idT43ofNzMUDFudmXAMDm8o1AYOr6QHUQPFU3JaldrY3D2O+gYIOKODCB3iwwAX-cczo5juDX9voO76Ve-dD5iwI+J9EpnyrHaVgl8y7Yw4DffQd8wYAzvIA363QL5w00G-D+LRv76CAA)

They have an opened issue regarding that, and I posted my examples there. While they investigate it, I'll try to find a way to handle that on our end. All help is welcome! I'll keep you posted. 

Unfortunately, typescript doesn't provide a way to suppress this warning via tsconfig. In the meantime, I'd advise you to wait a bit longer to use this feature (which is **optional** if you don't augment the Resources type) until we sort that out (for a large number of namespaces). This will be on the documentation as a limitation (for now).

**Comment by pedrodurek** [comment]
Hey @jigsawye, can we check if you're still getting the warning on the version 11.8.4?

**Comment by jigsawye** [comment]
@pedrodurek Thanks for your help. The type checking works fine now!

<img width="568" alt="screencapture 2020-12-15 上午10 59 16" src="https://user-images.githubusercontent.com/8567270/102167113-b2424180-3ec8-11eb-9691-f86ed74677a7.png">

<img width="416" alt="screencapture 2020-12-15 上午10 59 48" src="https://user-images.githubusercontent.com/8567270/102167118-b40c0500-3ec8-11eb-8b2c-0e7b8099d08e.png">

But I have another question.
It's about calling `useTranslation` with 1 namespace, using a string instead of an array.
It looks like the type checking will only pass without `namespace:` key:

<img width="379" alt="screencapture 2020-12-15 上午11 27 29" src="https://user-images.githubusercontent.com/8567270/102167269-0f3df780-3ec9-11eb-8214-971842e5bf96.png">

<img width="381" alt="screencapture 2020-12-15 上午11 33 18" src="https://user-images.githubusercontent.com/8567270/102167512-85425e80-3ec9-11eb-9577-e43d8e106246.png">

Please have a look thanks 😄

**Comment by pedrodurek** [comment]
Hi @jigsawye, I'm glad to hear that!
Regarding the other question, actually, the types were designed to work like that to prevent long compilation time, particularly on cases with thousands of keys, which would increase the compilation time drastically. We're gonna add those limitations on the documentation to avoid confusion. 
As the main problem was solved, can we close the issue?

**Comment by jigsawye** [comment]
@pedrodurek Sure! 😄

**Comment by tomasswood** [comment]
To add to this, you must import your translation files:
`import ns1 from './en/ns1.json';`

Requiring any of them will trigger the error as well:
`const ns1 = require('./en/ns1.json');`

**Comment by anteeek** [comment]
I had this error while using namespaces (as in Typescript section in docs) - I had a typo in `.json` import and every reference to that namespace threw this error. The cause was the typo - the `.json` file didn't exist

**Comment by renatobenks** [comment]
I'm still having this weird error, and it weirdly doesn't happen all the time, only for a specific case (not even line), and I don't have so many namespaces like mentioned previously, or I'm using namespace prefixes either, look out this example below:

<img width="1042" alt="Screen Shot 2021-11-25 at 21 19 59" src="https://user-images.githubusercontent.com/51369951/143509906-992a7b0c-6c65-4ea5-97d4-b5bf6a84d337.png">

any help would be awesome

**Comment by pedrodurek** [comment]
Hey @renatobenks, it may be a wrong configuration, could you share an example on codesandbox?

**Comment by jonguenther** [comment]
Hey, I am having a similar issue in VS Code using Typescript version `4.5.2`. Using a similar configuration as this [Codesandbox](https://codesandbox.io/s/react-i18next-type-excessively-deep-forked-61cju?file=/tsconfig.json) (only difference being that `react-i18next.d.ts` lives inside inside `src/@types`), TS throws an error when trying to use `useTranslation`

```tsx
import React from 'react';
import { useTranslation } from 'react-i18next';

const TestComponent = () => {
  const { t } = useTranslation(); // error occurs when trying to use useTranslation()
  return <>{t('test')}</>;
};
```

![image](https://user-images.githubusercontent.com/23116024/144003567-6cae8169-0532-4b8c-92ad-50dab164e3fd.png)

I am using `react-i18next` version `11.14.3`.

**Comment by pedrodurek** [comment]
Hey @jonguenther, I don't see any error on the link you provided (codesandbox)

**Comment by jonguenther** [comment]
@pedrodurek thanks for the reply, turns out I had a misconfiguration of `tsconfig.json` locally where I did not include`resolveJsonModule` and incorrectly imported the translation. It works now :)

**Comment by jamsmd** [comment]
An empty array in the translations file caused the error for me:
```
"Header": {
		"CTA": "Generate Domain Names",
		"NavItems": []
	}
```
Populating the array fixed the array

**Comment by tiavina-mika** [comment]
I'am having the same issue with `useTranslation`,
here is my resources
```
{
  "en": {
    "welcomeScreen": {
      "common": {
        "english": "English",
        "french": "French",
        "malagasy": "Malagasy",
      },
      "test": {
        "back": "Test in english",
      },
    },
  },
  "fr": {
    "welcomeScreen": {
      "common": {
        "english": "Anglais",
        "french": "Français",
        "malagasy": "Malgache",
      },
      "test": {
        "back": "Teste en Français",
      },
    },
  },
  "mg": Object {
    "welcomeScreen":  {
      "common":  {
        "english": "Anglisy",
        "french": "Frantsay",
        "malagasy": "Malagasy",
      },
      "test":  {
        "back": "Teste amin'ny malagasy",
      },
    },
  },
}
```

I am using "react-i18next": "^11.18.0"
