### ISSUE TITLE
v8.x: "Cannot read property 'usePureComponent' of undefined" in withNamespaces.js when nesting withNamespaces()

### ISSUE THREAD

**Issue by olivierpascal** [i18next/react-i18next#528]
Maybe withNamespaces does not pass i18nOptions through?

**Comment by olivierpascal** [comment]
To reproduce with `react_withHOC`:

1. Replace `reactI18nextModule` with `I18nextProvider`
2. Create a new component `Test.js` using `withNamespaces`, ie:

```javascript
import React from 'react';
import { withNamespaces } from 'react-i18next';

const Test = ({ t }) => (
  <div>Another description: {t('description.part2')}</div>
);

export default withNamespaces("translations")(Test);
```

3. Nest it inside `App.js` component
4. **BAM**

**Comment by raulfdm** [comment]
Maybe https://github.com/i18next/react-i18next/issues/355 related

**Comment by jamuhl** [comment]
@raulfdm not related to that...just a problem introduced with v8...currently working on a fix.

**Comment by raulfdm** [comment]
@jamuhl ohh I see.. I downgrade to v7 and start to work again 🤔 .. thanks btw

**Comment by jarnovanrhijn** [comment]
Having the same issue. i does however pass i18nOptions.

<img width="572" alt="screenshot 2018-10-02 at 10 41 53" src="https://user-images.githubusercontent.com/2767127/46338205-ce32d300-c62f-11e8-8ad0-823058a1c475.png">

The issue i'm facing is that props.i18n does not exist in NamespacesConsumer.js
<img width="747" alt="screenshot 2018-10-02 at 10 45 10" src="https://user-images.githubusercontent.com/2767127/46338386-574a0a00-c630-11e8-91eb-6c149eae3943.png">

Will downgrade for now.

**Comment by jamuhl** [comment]
should be fixed in react-i18next@8.0.5 - please verify

**Comment by olivierpascal** [comment]
Thanks! Well, this seems to be fixed but I have another bug, apparently related. Only in production, I still need some time to debug but I believe it comes from [utils::initSSR()](https://github.com/i18next/react-i18next/blob/60658921f659a8b56da9b4e1d8a5bd7a906096b6/src/utils.js#L26): `TypeError: Cannot set property 'wait' of undefined`

**Comment by olivierpascal** [comment]
That was quick!

**Comment by pepf** [comment]
> should be fixed in react-i18next@8.0.5 - please verify

Using 8.0.6 and cleared my caches, still getting the abovementioned error:
>ExceptionsManager.js:84 Unhandled JS Exception: TypeError: TypeError: TypeError: Cannot read property 'usePureComponent' of undefined

Some context:
<img width="912" alt="screen shot 2018-10-02 at 13 53 49" src="https://user-images.githubusercontent.com/1265435/46347115-b0269c00-c64a-11e8-8cfb-7c2edcbc74d0.png">

Using it in combination with:
```
    npmPackages:
      react: 16.3.1 => 16.3.1
      react-native: ~0.56.0 => 0.56.0
```

**Comment by jamuhl** [comment]
@pepf are you using `I18nextProvider` or the`.use(reactI18nextModule)` ?!? that really should not happen anymore...

**Comment by raulfdm** [comment]
@pepf usually when I have this weird situation I remove my `node_modules` and `yarn.lock` and install everything again. It solve's a lot of issues though 🤷‍♂️

**Comment by pepf** [comment]
I'm using the I18nextProvider, but I've been checking the source files, seems to be a caching issue still 😅 Thanks!

**Comment by jamuhl** [comment]
closing this for now....feel free to reopen if finding any other problem
